### ISSUE TITLE
Can't install PHP7, PHP5 works

### ISSUE THREAD

**Issue by crypticro** [cloudfoundry/binary-builder#42]
I tried to build the php buildpack using the binary-builder with oci-8 support. While it works for PHP 5.6 I am getting this error for php 7.

Extracting php-7.2.11.tar.gz into /tmp/x86_64-linux-gnu/ports/php7/7.2.11... OK
Running 'configure' for php7 7.2.11... OK
Running 'compile' for php7 7.2.11... OK
Running 'install' for php7 7.2.11... OK
Activating php7 7.2.11 (from ports/x86_64-linux-gnu/php7/7.2.11)...
cp: cannot stat '/usr/local/lib/x86_64-linux-gnu/librabbitmq.so*': No such file or directory
cp: cannot stat '/lib/libhiredis.so*': No such file or directory
cp: cannot stat '/lib/libmemcached.so*': No such file or directory
cp: cannot stat '/usr/local/lib/x86_64-linux-gnu/libcassandra.so*': No such file or directory
cp: cannot stat '/usr/lib/librdkafka.so*': No such file or directory
cp: cannot stat '/ioncube/ioncube_loader_lin_7.2.so': No such file or directory
bundler: failed to load command: ./bin/binary-builder.rb (./bin/binary-builder.rb)
NoMethodError: undefined method `setup_tar' for nil:NilClass
  /binary-builder/recipe/php_meal.rb:82:in `setup_tar'
  /binary-builder/lib/archive_recipe.rb:13:in `compress!'
  /binary-builder/bin/binary-builder.rb:87:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/bundler-1.16.6/lib/bundler.rb:299:in `block in with_clean_env'
  /usr/lib/ruby/gems/2.3.0/gems/bundler-1.16.6/lib/bundler.rb:544:in `with_env'
  /usr/lib/ruby/gems/2.3.0/gems/bundler-1.16.6/lib/bundler.rb:299:in `with_clean_env'
  /binary-builder/bin/binary-builder.rb:83:in `<top (required)>'

Any ideas why it fails?

**Comment by dmikusa-pivotal** [comment]
What command are you running to perform the build?

**Comment by crypticro** [comment]
@dmikusa-pivotal the command was the following:

docker run -w /binary-builder -v `pwd`:/binary-builder -v /usr/local/lib/oracle:/oracle -it cloudfoundry/cflinuxfs2 bash ./bin/binary-builder --name=php7 --version=7.2.11 --sha256=3e773300bd2507524d3f67489ab44394d8344ac96678b0ad9d94b910d32e617d

**Comment by dmikusa-pivotal** [comment]
Oh, I think I see it now. You need `--php-extensions-file=./php-extensions.yml`.

There's a YAML file you need to include that tells the builder which PHP extensions & supporting libraries to build. It seems to be failing because it can't find a lot of those. See this doc link for an example.

https://github.com/cloudfoundry/binary-builder#building-php

I think it's failing here.

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php_meal.rb#L82

It only gets to that line when Oracle support is enabled, but when it's looking through the list of extensions to build it doesn't find the Oracle extensions. Minimally the file I mentioned above needs to include `oci8` and `pdo_oci`.

I think that should make it work.

**Comment by crypticro** [comment]
@dmikusa-pivotal any idea what the extension file looks like because the sample in the documentation is a dead link. Actually building it works for PHP 5.6 without the extensions option.

**Comment by dmikusa-pivotal** [comment]
I have a PR to fix that -> https://github.com/cloudfoundry/binary-builder/pull/39

New links should be there.

**Comment by crypticro** [comment]
@dmikusa-pivotal thanks it now worked using the new files. I created php7-7.2.9-linux-x64.tgz

Is there any documentation how to add that binary to the manifest? I tried doing the following:
applications:
llowing:

applications:
- name: appname
  buildpacks:
  - https://[host]/php7-7.2.9-linux-x64.tgz

But it just ignored that and install the default php version. when running "cf push"

**Comment by dmikusa-pivotal** [comment]
What I typically do is to edit one of the existing entries. The entry in question will look like this:

```
- name: php
  version: 7.2.11
  uri: https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.11-linux-x64-cflinuxfs2-edb4c018.tgz
  sha256: edb4c01889a651e06d06e1d9547fc402aa8e7276187b69f5404442f83193c7ad
  cf_stacks:
  - cflinuxfs2
  modules:
  - amqp
  - apcu
  - bz2
  - cassandra
  - curl
  - dba
  - exif
  - fileinfo
  - ftp
  - gd
  - geoip
  - gettext
  - gmp
  - igbinary
  - imagick
  - imap
  - ioncube
  - ldap
  - lua
  - lzf
  - mailparse
  - mbstring
  - memcached
  - mongodb
  - msgpack
  - mysqli
  - oauth
  - opcache
  - openssl
  - pcntl
  - pdo
  - pdo_mysql
  - pdo_odbc
  - pdo_pgsql
  - pdo_sqlite
  - pgsql
  - phalcon
  - phpiredis
  - protobuf
  - pspell
  - rdkafka
  - readline
  - redis
  - shmop
  - snmp
  - soap
  - sockets
  - sodium
  - stomp
  - sysvmsg
  - sysvsem
  - sysvshm
  - tideways
  - tideways_xhprof
  - xdebug
  - xsl
  - yaf
  - yaml
  - zip
  - zlib
```

Minimally you need to update the URL to point to your custom build and you need to add a sha256 hash for your build. Beyond that, you might also update the version if you compiled a different PHP version or the list of extensions if you added new extensions. The list of extensions must have all the extensions compiled into PHP as the buildpack uses this list to determine what extensions are included with PHP.

Oh, at the moment there are also two of each version in the manifest.yml because we're supporting both cflinuxfs2 and cflinuxfs3. Just update the one that you're building/using.
